# Generated by Codex on 2026-06-05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


DEFAULT_TEMPLATES = {
    "user.email_confirmation": {
        "pt-br": {
            "subject": "Confirme seu email no GoTrendLabs",
            "body_text": (
                "Olá {{ display_name }},\n\n"
                "Bem-vindo ao GoTrendLabs. Confirme seu email para liberar todas as ações da conta:\n"
                "{{ confirmation_url }}\n\n"
                "Este link expira em {{ expires_hours }} horas."
            ),
        },
        "en": {
            "subject": "Confirm your GoTrendLabs email",
            "body_text": (
                "Hi {{ display_name }},\n\n"
                "Welcome to GoTrendLabs. Confirm your email to unlock all account actions:\n"
                "{{ confirmation_url }}\n\n"
                "This link expires in {{ expires_hours }} hours."
            ),
        },
    },
    "account.password_reset": {
        "pt-br": {
            "subject": "Recupere sua senha no GoTrendLabs",
            "body_text": (
                "Olá {{ display_name }},\n\n"
                "Recebemos uma solicitação para redefinir sua senha. Use o link abaixo:\n"
                "{{ reset_url }}\n\n"
                "Este link expira em {{ expires_minutes }} minutos. Se você não pediu isso, ignore este email."
            ),
        },
        "en": {
            "subject": "Reset your GoTrendLabs password",
            "body_text": (
                "Hi {{ display_name }},\n\n"
                "We received a request to reset your password. Use the link below:\n"
                "{{ reset_url }}\n\n"
                "This link expires in {{ expires_minutes }} minutes. If you did not request this, ignore this email."
            ),
        },
    },
    "market.locked": {
        "pt-br": {
            "subject": "Mercado fechado: {{ market_title }}",
            "body_text": "O mercado \"{{ market_title }}\" foi fechado para novas previsões.\n\nAcompanhe o resultado em {{ market_url }}.",
        },
        "en": {
            "subject": "Market locked: {{ market_title }}",
            "body_text": "The market \"{{ market_title }}\" is now closed for new predictions.\n\nFollow the result at {{ market_url }}.",
        },
    },
    "market.resolved": {
        "pt-br": {
            "subject": "Mercado resolvido: {{ market_title }}",
            "body_text": "O mercado \"{{ market_title }}\" foi resolvido.\n\nResultado: {{ winning_option }}\nVeja os detalhes em {{ market_url }}.",
        },
        "en": {
            "subject": "Market resolved: {{ market_title }}",
            "body_text": "The market \"{{ market_title }}\" has been resolved.\n\nOutcome: {{ winning_option }}\nSee details at {{ market_url }}.",
        },
    },
    "wallet.credited": {
        "pt-br": {
            "subject": "Créditos concedidos no GoTrendLabs",
            "body_text": "Você recebeu {{ amount }} GT₵.\n\nMotivo: {{ description }}\nVeja sua carteira em {{ wallet_url }}.",
        },
        "en": {
            "subject": "Credits granted on GoTrendLabs",
            "body_text": "You received {{ amount }} GT₵.\n\nReason: {{ description }}\nSee your wallet at {{ wallet_url }}.",
        },
    },
}


def seed_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("communications", "EmailTemplate")
    now = django.utils.timezone.now()
    for key, locales in DEFAULT_TEMPLATES.items():
        for locale, payload in locales.items():
            EmailTemplate.objects.update_or_create(
                key=key,
                locale=locale,
                defaults={
                    "subject": payload["subject"],
                    "body_text": payload["body_text"],
                    "body_html": "",
                    "is_active": True,
                    "created_at": now,
                    "updated_at": now,
                },
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDelivery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(max_length=80)),
                ("recipient_email", models.EmailField(max_length=254)),
                ("template_key", models.CharField(max_length=80)),
                ("locale", models.CharField(default="pt-br", max_length=10)),
                ("subject", models.CharField(blank=True, max_length=255)),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("idempotency_key", models.CharField(max_length=191, unique=True)),
                ("status", models.CharField(choices=[("queued", "Queued"), ("sending", "Sending"), ("sent", "Sent"), ("failed", "Failed"), ("suppressed", "Suppressed")], default="queued", max_length=20)),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("next_attempt_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="email_deliveries", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "gotrendlabs_email_deliveries",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=80)),
                ("locale", models.CharField(choices=[("pt-br", "PT-BR"), ("en", "EN")], default="pt-br", max_length=10)),
                ("subject", models.CharField(max_length=255)),
                ("body_text", models.TextField()),
                ("body_html", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_email_templates", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "gotrendlabs_email_templates",
                "ordering": ["key", "locale"],
            },
        ),
        migrations.CreateModel(
            name="EmailConfirmationToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="email_confirmation_tokens", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "gotrendlabs_email_confirmation_tokens",
            },
        ),
        migrations.AddIndex(model_name="emaildelivery", index=models.Index(fields=["status", "next_attempt_at"], name="gotrendlabs_status_02b521_idx")),
        migrations.AddIndex(model_name="emaildelivery", index=models.Index(fields=["recipient_user", "-created_at"], name="gotrendlabs_recipie_19463e_idx")),
        migrations.AddIndex(model_name="emaildelivery", index=models.Index(fields=["event_type", "-created_at"], name="gotrendlabs_event_t_54701c_idx")),
        migrations.AddConstraint(model_name="emailtemplate", constraint=models.UniqueConstraint(fields=("key", "locale"), name="uniq_email_template_key_locale")),
        migrations.AddIndex(model_name="emailtemplate", index=models.Index(fields=["key", "locale", "is_active"], name="gotrendlabs_key_fff6d3_idx")),
        migrations.AddIndex(model_name="emailconfirmationtoken", index=models.Index(fields=["token_hash"], name="gotrendlabs_token_h_339c60_idx")),
        migrations.AddIndex(model_name="emailconfirmationtoken", index=models.Index(fields=["user", "used_at", "expires_at"], name="gotrendlabs_user_id_d34ae3_idx")),
        migrations.RunPython(seed_email_templates, migrations.RunPython.noop),
    ]
