# Generated by Django 4.2.30 on 2026-05-17 20:41

import json
import re
import unicodedata
from pathlib import Path

from django.db import migrations, models
import django.db.models.deletion


def _slug(value):
    normalized = unicodedata.normalize("NFKD", value or "")
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii")
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_value.lower()).strip("-")
    return slug or "geral"


def seed_markets(apps, schema_editor):
    MarketCategory = apps.get_model("markets", "MarketCategory")
    MarketSubcategory = apps.get_model("markets", "MarketSubcategory")
    Market = apps.get_model("markets", "Market")
    MarketOption = apps.get_model("markets", "MarketOption")

    fixture_path = Path(__file__).resolve().parents[2] / "data" / "fixtures" / "domain.json"
    with fixture_path.open(encoding="utf-8") as fixture:
        markets = json.load(fixture)["markets"]

    for index, payload in enumerate(markets, start=1):
        category, _ = MarketCategory.objects.update_or_create(
            slug=_slug(payload["category"]),
            defaults={"name": payload["category"]},
        )
        subcategory, _ = MarketSubcategory.objects.update_or_create(
            category=category,
            slug=_slug(payload["subcategory"]),
            defaults={"name": payload["subcategory"]},
        )
        market, _ = Market.objects.update_or_create(
            slug=payload["slug"],
            defaults={
                "category": category,
                "subcategory": subcategory,
                "title": payload["title"],
                "summary": payload.get("summary", ""),
                "kind": payload["kind"],
                "status": payload["status"],
                "status_label": payload.get("status_label", payload["status"]),
                "primary_outcome": payload.get("primary_outcome", ""),
                "primary_probability": payload.get("primary_probability", 0),
                "secondary_probability": payload.get("secondary_probability", 0),
                "volume_oc": payload.get("volume_oc", ""),
                "participants": payload.get("participants", ""),
                "source": payload.get("source", ""),
                "closes_in": payload.get("closes_in", ""),
                "close_label": payload.get("close_label", ""),
                "thumb": payload.get("thumb", ""),
                "thumb_color": payload.get("thumb_color", ""),
                "resolution_criteria": payload.get("resolution_criteria", ""),
                "resolution_type": payload.get("resolution_type", ""),
                "resolution_note": payload.get("resolution_note", ""),
                "display_order": index,
            },
        )
        for option_index, option in enumerate(payload.get("options", []), start=1):
            MarketOption.objects.update_or_create(
                market=market,
                label=option["label"],
                defaults={
                    "probability": option.get("probability", 0),
                    "hint": option.get("hint", ""),
                    "display_order": option_index,
                },
            )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('binary', 'Binary'), ('multiple', 'Multiple')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('open', 'Open'), ('locked', 'Locked'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], db_index=True, max_length=20)),
                ('status_label', models.CharField(max_length=80)),
                ('primary_outcome', models.CharField(max_length=80)),
                ('primary_probability', models.PositiveSmallIntegerField(default=0)),
                ('secondary_probability', models.PositiveSmallIntegerField(default=0)),
                ('volume_oc', models.CharField(blank=True, max_length=80)),
                ('participants', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(blank=True, max_length=180)),
                ('closes_in', models.CharField(blank=True, max_length=40)),
                ('close_label', models.CharField(blank=True, max_length=120)),
                ('thumb', models.CharField(blank=True, max_length=12)),
                ('thumb_color', models.CharField(blank=True, max_length=20)),
                ('resolution_criteria', models.TextField(blank=True)),
                ('resolution_type', models.CharField(blank=True, max_length=40)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orynth_markets',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orynth_market_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='markets.marketcategory')),
            ],
            options={
                'db_table': 'orynth_market_subcategories',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('probability', models.PositiveSmallIntegerField(default=0)),
                ('hint', models.CharField(blank=True, max_length=160)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='markets.market')),
            ],
            options={
                'db_table': 'orynth_market_options',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='market',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='markets.marketcategory'),
        ),
        migrations.AddField(
            model_name='market',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='markets.marketsubcategory'),
        ),
        migrations.AddField(
            model_name='market',
            name='winning_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_markets', to='markets.marketoption'),
        ),
        migrations.AddConstraint(
            model_name='marketsubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uniq_market_subcategory_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='marketoption',
            constraint=models.UniqueConstraint(fields=('market', 'label'), name='uniq_market_option_market_label'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['status', 'display_order'], name='orynth_mark_status_55fd9b_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['category', 'status'], name='orynth_mark_categor_5687eb_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['subcategory', 'status'], name='orynth_mark_subcate_2df3e6_idx'),
        ),
        migrations.RunPython(seed_markets, migrations.RunPython.noop),
    ]
