# Generated by Django 4.2.30 on 2026-05-17 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('title', models.CharField(max_length=240)),
                ('summary', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('binary', 'Binary'), ('multiple', 'Multiple')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('open', 'Open'), ('locked', 'Locked'), ('resolved', 'Resolved'), ('canceled', 'Canceled')], db_index=True, max_length=20)),
                ('status_label', models.CharField(max_length=80)),
                ('primary_outcome', models.CharField(max_length=80)),
                ('primary_probability', models.PositiveSmallIntegerField(default=0)),
                ('secondary_probability', models.PositiveSmallIntegerField(default=0)),
                ('volume_oc', models.CharField(blank=True, max_length=80)),
                ('participants', models.CharField(blank=True, max_length=80)),
                ('source', models.CharField(blank=True, max_length=180)),
                ('closes_in', models.CharField(blank=True, max_length=40)),
                ('close_label', models.CharField(blank=True, max_length=120)),
                ('thumb', models.CharField(blank=True, max_length=12)),
                ('thumb_color', models.CharField(blank=True, max_length=20)),
                ('resolution_criteria', models.TextField(blank=True)),
                ('resolution_type', models.CharField(blank=True, max_length=40)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orynth_markets',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'orynth_market_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MarketSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='markets.marketcategory')),
            ],
            options={
                'db_table': 'orynth_market_subcategories',
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MarketOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('probability', models.PositiveSmallIntegerField(default=0)),
                ('hint', models.CharField(blank=True, max_length=160)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='markets.market')),
            ],
            options={
                'db_table': 'orynth_market_options',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='market',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='markets.marketcategory'),
        ),
        migrations.AddField(
            model_name='market',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='markets', to='markets.marketsubcategory'),
        ),
        migrations.AddField(
            model_name='market',
            name='winning_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winning_markets', to='markets.marketoption'),
        ),
        migrations.AddConstraint(
            model_name='marketsubcategory',
            constraint=models.UniqueConstraint(fields=('category', 'slug'), name='uniq_market_subcategory_category_slug'),
        ),
        migrations.AddConstraint(
            model_name='marketoption',
            constraint=models.UniqueConstraint(fields=('market', 'label'), name='uniq_market_option_market_label'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['status', 'display_order'], name='orynth_mark_status_55fd9b_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['category', 'status'], name='orynth_mark_categor_5687eb_idx'),
        ),
        migrations.AddIndex(
            model_name='market',
            index=models.Index(fields=['subcategory', 'status'], name='orynth_mark_subcate_2df3e6_idx'),
        ),
    ]
