# Generated by Codex on 2026-05-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("markets", "0004_taxonomy_blocking"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("question", models.CharField(max_length=240)),
                ("category", models.CharField(max_length=80)),
                ("subcategory", models.CharField(blank=True, max_length=80)),
                ("kind", models.CharField(choices=[("binary", "Binary"), ("multiple", "Multiple")], default="binary", max_length=20)),
                ("suggested_source", models.CharField(max_length=180)),
                ("rationale", models.TextField(blank=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("converted", "Converted"), ("rejected", "Rejected")], db_index=True, default="pending", max_length=20)),
                ("admin_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="market_suggestions", to=settings.AUTH_USER_MODEL)),
                ("converted_market", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="source_suggestions", to="markets.market")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_suggestions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "orynth_market_suggestions",
            },
        ),
        migrations.CreateModel(
            name="ProductFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("feedback_type", models.CharField(max_length=80)),
                ("severity", models.CharField(choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")], db_index=True, default="medium", max_length=20)),
                ("description", models.TextField()),
                ("status", models.CharField(choices=[("pending", "Pending"), ("reviewed", "Reviewed"), ("rewarded", "Rewarded"), ("rejected", "Rejected")], db_index=True, default="pending", max_length=20)),
                ("admin_note", models.TextField(blank=True)),
                ("reward_oc", models.PositiveIntegerField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("rewarded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="product_feedback", to=settings.AUTH_USER_MODEL)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_feedback", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "orynth_product_feedback",
            },
        ),
        migrations.AddIndex(
            model_name="marketsuggestion",
            index=models.Index(fields=["status", "-created_at"], name="orynth_mark_status_232638_idx"),
        ),
        migrations.AddIndex(
            model_name="marketsuggestion",
            index=models.Index(fields=["author", "-created_at"], name="orynth_mark_author__3604fd_idx"),
        ),
        migrations.AddIndex(
            model_name="productfeedback",
            index=models.Index(fields=["status", "-created_at"], name="orynth_prod_status_55d5ea_idx"),
        ),
        migrations.AddIndex(
            model_name="productfeedback",
            index=models.Index(fields=["severity", "status"], name="orynth_prod_severit_57fcbc_idx"),
        ),
        migrations.AddIndex(
            model_name="productfeedback",
            index=models.Index(fields=["author", "-created_at"], name="orynth_prod_author__b5d962_idx"),
        ),
    ]
