# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0005_operational_queues"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketsuggestion",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="marketsuggestion",
            name="guest_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="marketsuggestion",
            name="reward_gtl",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketsuggestion",
            name="rewarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productfeedback",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="productfeedback",
            name="guest_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="marketsuggestion",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewed", "Reviewed"),
                    ("converted", "Converted"),
                    ("rewarded", "Rewarded"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
