# Generated by Codex on 2026-05-18

from django.db import migrations, models


def backfill_probability_exact(apps, schema_editor):
    Market = apps.get_model("markets", "Market")
    MarketOption = apps.get_model("markets", "MarketOption")
    for option in MarketOption.objects.all().iterator():
        option.probability_exact = option.probability
        option.save(update_fields=["probability_exact"])
    for market in Market.objects.all().iterator():
        market.primary_probability_exact = market.primary_probability
        market.secondary_probability_exact = market.secondary_probability
        market.save(update_fields=["primary_probability_exact", "secondary_probability_exact"])


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0007_prediction"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="primary_probability_exact",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="market",
            name="secondary_probability_exact",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AddField(
            model_name="marketoption",
            name="probability_exact",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.RunPython(backfill_probability_exact, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="prediction",
            name="probability_at_entry",
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
