# Generated by Codex on 2026-05-18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("markets", "0009_remove_market_primary_probability_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[("visible", "Visible"), ("hidden", "Hidden")],
                        db_index=True,
                        default="visible",
                        max_length=20,
                    ),
                ),
                ("moderation_note", models.TextField(blank=True)),
                ("moderated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="market_comments", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "market",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="markets.market"),
                ),
                (
                    "moderated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderated_market_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gotrendlabs_market_comments",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["market", "status", "-created_at"], name="gtl_mark_mkt_f9e441_idx"),
                    models.Index(fields=["author", "-created_at"], name="gtl_mark_auth_e373b2_idx"),
                    models.Index(fields=["status", "-created_at"], name="gtl_mark_stat_1e4f0e_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CommentReaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "reaction",
                    models.CharField(choices=[("like", "Like"), ("dislike", "Dislike")], max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "comment",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="reactions", to="markets.marketcomment"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comment_reactions", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "gotrendlabs_comment_reactions",
                "indexes": [
                    models.Index(fields=["comment", "reaction"], name="gtl_comm_cmt_e86827_idx"),
                    models.Index(fields=["user", "-created_at"], name="gtl_comm_user_53c6e6_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("comment", "user"), name="uniq_comment_reaction_comment_user"),
                ],
            },
        ),
    ]
