# Generated by Codex on 2026-05-18

from django.db import migrations, models


def keep_single_featured_market(apps, schema_editor):
    Market = apps.get_model("markets", "Market")
    featured = list(Market.objects.filter(is_featured=True).order_by("display_order", "id").values_list("id", flat=True))
    if len(featured) > 1:
        Market.objects.filter(is_featured=True).exclude(id=featured[0]).update(is_featured=False)


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0010_market_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="is_featured",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(keep_single_featured_market, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="market",
            constraint=models.UniqueConstraint(
                condition=models.Q(is_featured=True),
                fields=("is_featured",),
                name="uniq_single_featured_market",
            ),
        ),
    ]
