# Generated by Codex on 2026-05-22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("markets", "0020_category_subcategory_notice"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiAgent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120)),
                ("agent_type", models.CharField(choices=[("analyst", "Analyst"), ("liquidity", "Liquidity"), ("contrarian", "Contrarian")], db_index=True, max_length=32)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("personality_prompt", models.TextField(blank=True)),
                ("comment_style", models.CharField(blank=True, max_length=120)),
                ("max_comments_per_day", models.PositiveIntegerField(blank=True, null=True)),
                ("max_predictions_per_day", models.PositiveIntegerField(blank=True, null=True)),
                ("max_stake_oc", models.PositiveIntegerField(blank=True, null=True)),
                ("cooldown_hours", models.PositiveIntegerField(blank=True, null=True)),
                ("min_humans_for_prediction", models.PositiveIntegerField(blank=True, null=True)),
                ("last_action_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="ai_agent", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "orynth_ai_agents",
                "ordering": ["agent_type", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="AiAgentAction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("action_type", models.CharField(choices=[("comment", "Comment"), ("prediction", "Prediction"), ("cycle", "Cycle")], db_index=True, max_length=32)),
                ("status", models.CharField(choices=[("created", "Created"), ("skipped", "Skipped"), ("failed", "Failed")], db_index=True, max_length=32)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("payload_summary", models.JSONField(blank=True, default=dict)),
                ("prompt_template_version", models.CharField(blank=True, max_length=64)),
                ("prompt_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("agent", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="actions", to="agents.aiagent")),
                ("comment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_agent_actions", to="markets.marketcomment")),
                ("market", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_agent_actions", to="markets.market")),
                ("prediction", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ai_agent_actions", to="markets.prediction")),
            ],
            options={
                "db_table": "orynth_ai_agent_actions",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(model_name="aiagent", index=models.Index(fields=["agent_type", "is_active"], name="orynth_ai__agent_t_3d7e5d_idx")),
        migrations.AddIndex(model_name="aiagent", index=models.Index(fields=["user"], name="orynth_ai__user_id_ef9014_idx")),
        migrations.AddIndex(model_name="aiagentaction", index=models.Index(fields=["agent", "-created_at"], name="orynth_ai__agent_i_8e25e8_idx")),
        migrations.AddIndex(model_name="aiagentaction", index=models.Index(fields=["market", "-created_at"], name="orynth_ai__market__2a894d_idx")),
        migrations.AddIndex(model_name="aiagentaction", index=models.Index(fields=["action_type", "status", "-created_at"], name="orynth_ai__action__7aab81_idx")),
    ]
