# Generated by Django 4.2.30 on 2026-05-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiagent',
            new_name='orynth_ai_a_agent_t_123d2a_idx',
            old_name='orynth_ai__agent_t_3d7e5d_idx',
        ),
        migrations.RenameIndex(
            model_name='aiagent',
            new_name='orynth_ai_a_user_id_6d2406_idx',
            old_name='orynth_ai__user_id_ef9014_idx',
        ),
        migrations.RenameIndex(
            model_name='aiagentaction',
            new_name='orynth_ai_a_agent_i_d27b1a_idx',
            old_name='orynth_ai__agent_i_8e25e8_idx',
        ),
        migrations.RenameIndex(
            model_name='aiagentaction',
            new_name='orynth_ai_a_market__b7b7a2_idx',
            old_name='orynth_ai__market__2a894d_idx',
        ),
        migrations.RenameIndex(
            model_name='aiagentaction',
            new_name='orynth_ai_a_action__268d47_idx',
            old_name='orynth_ai__action__7aab81_idx',
        ),
    ]
