# Generated by Django 4.2.30 on 2026-06-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_rename_gotrendlabs_ai__agent_t_3d7e5d_idx_gotrendlabs_ai_a_agent_t_123d2a_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aiagent',
            old_name='max_stake_oc',
            new_name='max_stake_gtl',
        ),
        migrations.RenameIndex(
            model_name='aiagent',
            new_name='gotrendlabs_agent_t_506108_idx',
            old_name='orynth_ai_a_agent_t_123d2a_idx',
        ),
        migrations.RenameIndex(
            model_name='aiagent',
            new_name='gotrendlabs_user_id_74c996_idx',
            old_name='orynth_ai_a_user_id_6d2406_idx',
        ),
        migrations.RenameIndex(
            model_name='aiagentaction',
            new_name='gotrendlabs_agent_i_0bf6dc_idx',
            old_name='orynth_ai_a_agent_i_d27b1a_idx',
        ),
        migrations.RenameIndex(
            model_name='aiagentaction',
            new_name='gotrendlabs_market__a9d039_idx',
            old_name='orynth_ai_a_market__b7b7a2_idx',
        ),
        migrations.RenameIndex(
            model_name='aiagentaction',
            new_name='gotrendlabs_action__f8145b_idx',
            old_name='orynth_ai_a_action__268d47_idx',
        ),
        migrations.AlterModelTable(
            name='aiagent',
            table='gotrendlabs_ai_agents',
        ),
        migrations.AlterModelTable(
            name='aiagentaction',
            table='gotrendlabs_ai_agent_actions',
        ),
    ]
