# Generated by Django 4.2.30 on 2026-10-07 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("markets", "0031_integrity_ledger_checkpoints"),
    ]

    operations = [
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("secret_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                ("last_used_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "gotrendlabs_agent_credentials",
            },
        ),
        migrations.CreateModel(
            name="EditorialDraft",
            fields=[
                (
                    "market",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        serialize=False,
                        to="markets.market",
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1)),
                ("state", models.CharField(default="preparation", max_length=16)),
                ("record", models.JSONField(default=dict)),
                ("snapshot_hash", models.CharField(max_length=64)),
                ("decision", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "gotrendlabs_agent_editorial_drafts",
            },
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scopes", models.JSONField(default=list)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gotrendlabs_agent_grants",
            },
        ),
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(default="", max_length=1000)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("active", "active"),
                            ("paused", "paused"),
                            ("revoked", "revoked"),
                        ],
                        default="paused",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("scopes", models.JSONField(default=list)),
                ("drafts_per_day", models.PositiveIntegerField(default=5)),
                ("calls_per_minute", models.PositiveIntegerField(default=60)),
                ("concurrent_calls", models.PositiveIntegerField(default=2)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used_at", models.DateTimeField(null=True)),
                (
                    "responsible",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gotrendlabs_agent_integrations",
            },
        ),
        migrations.CreateModel(
            name="OAuthClient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("redirect_uris", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "gotrendlabs_agent_oauth_clients",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("kind", models.CharField(max_length=16)),
                ("issuer", models.CharField(max_length=255)),
                ("audience", models.CharField(max_length=255)),
                ("scopes", models.JSONField(default=list)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
                (
                    "credential",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="editorial_integrations.credential",
                    ),
                ),
                (
                    "grant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="editorial_integrations.grant",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="editorial_integrations.integration",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="editorial_integrations.token",
                    ),
                ),
            ],
            options={
                "db_table": "gotrendlabs_agent_tokens",
            },
        ),
        migrations.CreateModel(
            name="Quota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.CharField(max_length=150, unique=True)),
                ("count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField()),
                (
                    "integration",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="editorial_integrations.integration",
                    ),
                ),
            ],
            options={
                "db_table": "gotrendlabs_agent_quotas",
            },
        ),
        migrations.CreateModel(
            name="Lease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="editorial_integrations.integration",
                    ),
                ),
            ],
            options={
                "db_table": "gotrendlabs_agent_leases",
            },
        ),
        migrations.CreateModel(
            name="IngestedEvent",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="editorial_integrations.integration",
                    ),
                ),
            ],
            options={
                "db_table": "gotrendlabs_agent_ingested_events",
            },
        ),
        migrations.CreateModel(
            name="Idempotency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operation", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=100)),
                ("payload_hash", models.CharField(max_length=64)),
                ("response", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="editorial_integrations.integration",
                    ),
                ),
            ],
            options={
                "db_table": "gotrendlabs_agent_idempotency",
            },
        ),
        migrations.AddField(
            model_name="grant",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="editorial_integrations.oauthclient",
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="editorial_integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="grant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="EditorialRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("snapshot_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="editorial_integrations.editorialdraft",
                    ),
                ),
            ],
            options={
                "db_table": "gotrendlabs_agent_editorial_revisions",
            },
        ),
        migrations.AddField(
            model_name="editorialdraft",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="editorial_integrations.integration",
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="integration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="editorial_integrations.integration",
            ),
        ),
        migrations.AddConstraint(
            model_name="token",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("credential__isnull", False), ("grant__isnull", True)),
                    models.Q(("credential__isnull", True), ("grant__isnull", False)),
                    _connector="OR",
                ),
                name="agent_token_origin",
            ),
        ),
        migrations.AddIndex(
            model_name="integration",
            index=models.Index(
                fields=["state", "expires_at"], name="gotrendlabs_state_22122e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="idempotency",
            constraint=models.UniqueConstraint(
                fields=("integration", "operation", "key"),
                name="agent_idempotency_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="editorialrevision",
            constraint=models.UniqueConstraint(
                fields=("draft", "revision"), name="agent_editorial_revision_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="editorialdraft",
            index=models.Index(
                fields=["state", "market"], name="gotrendlabs_state_994979_idx"
            ),
        ),
    ]
