# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_ops", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="wallet_recharge_min_balance_gtl",
            field=models.PositiveIntegerField(default=100),
        ),
    ]
