# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_ops", "0002_siteconfig_wallet_recharge_min_balance_oc"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="daemon_missing_after_minutes",
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="daemon_stale_after_minutes",
            field=models.PositiveIntegerField(default=5),
        ),
    ]
