# Generated by Codex on 2026-05-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_ops", "0003_siteconfig_daemon_status_thresholds"),
    ]

    operations = [
        migrations.AddField(model_name="siteconfig", name="ai_agents_enabled", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="siteconfig", name="ai_commenting_enabled", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="siteconfig", name="ai_predictions_enabled", field=models.BooleanField(default=False)),
        migrations.AddField(model_name="siteconfig", name="ai_llm_provider", field=models.CharField(default="openai", max_length=40)),
        migrations.AddField(model_name="siteconfig", name="ai_llm_base_url", field=models.URLField(default="https://api.openai.com/v1")),
        migrations.AddField(model_name="siteconfig", name="ai_model", field=models.CharField(default="gpt-5.4-mini", max_length=120)),
        migrations.AddField(model_name="siteconfig", name="ai_high_reasoning_model", field=models.CharField(default="gpt-5.5", max_length=120)),
        migrations.AddField(model_name="siteconfig", name="ai_market_cooldown_hours", field=models.PositiveIntegerField(default=24)),
        migrations.AddField(model_name="siteconfig", name="ai_max_comments_per_market_per_day", field=models.PositiveIntegerField(default=1)),
        migrations.AddField(model_name="siteconfig", name="ai_max_comments_per_cycle", field=models.PositiveIntegerField(default=1)),
        migrations.AddField(model_name="siteconfig", name="ai_max_comments_per_day", field=models.PositiveIntegerField(default=20)),
        migrations.AddField(model_name="siteconfig", name="ai_comment_max_chars", field=models.PositiveIntegerField(default=700)),
        migrations.AddField(model_name="siteconfig", name="ai_min_humans_for_prediction", field=models.PositiveIntegerField(default=1)),
        migrations.AddField(model_name="siteconfig", name="ai_max_stake_gtl", field=models.PositiveIntegerField(default=25)),
        migrations.AddField(model_name="siteconfig", name="ai_max_predictions_per_cycle", field=models.PositiveIntegerField(default=1)),
        migrations.AddField(model_name="siteconfig", name="ai_max_predictions_per_day", field=models.PositiveIntegerField(default=10)),
        migrations.AddField(model_name="siteconfig", name="ai_skip_if_human_comments_recent", field=models.BooleanField(default=True)),
        migrations.AddField(model_name="siteconfig", name="ai_recent_human_comment_window_hours", field=models.PositiveIntegerField(default=6)),
        migrations.AddField(model_name="siteconfig", name="ai_openai_timeout_seconds", field=models.PositiveIntegerField(default=20)),
        migrations.AddField(model_name="siteconfig", name="ai_openai_max_retries", field=models.PositiveIntegerField(default=1)),
        migrations.AddField(model_name="siteconfig", name="ai_paused_until", field=models.DateTimeField(blank=True, null=True)),
        migrations.AddField(model_name="siteconfig", name="ai_pause_reason", field=models.TextField(blank=True, default="")),
    ]
