# Generated by Django 4.2.30 on 2026-06-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0006_siteconfig_log_retention_days'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='ai_max_stake_oc',
            new_name='ai_max_stake_gtl',
        ),
        migrations.RenameField(
            model_name='siteconfig',
            old_name='wallet_recharge_min_balance_oc',
            new_name='wallet_recharge_min_balance_gtl',
        ),
        migrations.AlterModelTable(
            name='siteconfig',
            table='gotrendlabs_site_config',
        ),
    ]
