# Generated by Django 4.2.30 on 2026-05-17 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_externalidentity_authsession_authevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('strong_category', models.CharField(blank=True, max_length=80)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_user_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=60)),
                ('title', models.CharField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_type', models.CharField(blank=True, max_length=60)),
                ('reference_id', models.CharField(blank=True, max_length=120)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_user_activities',
            },
        ),
        migrations.CreateModel(
            name='WalletLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(max_length=40)),
                ('amount', models.IntegerField()),
                ('direction', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('lock', 'Lock'), ('release', 'Release')], max_length=16)),
                ('description', models.CharField(max_length=255)),
                ('reference_type', models.CharField(blank=True, max_length=60)),
                ('reference_id', models.CharField(blank=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_ledger', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_wallet_ledger',
                'indexes': [models.Index(fields=['user', '-created_at'], name='gotrendlabs_user_id_33c3db_idx'), models.Index(fields=['entry_type', '-created_at'], name='gotrendlabs_entry_t_431ab3_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserReputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reputation_score', models.PositiveIntegerField(default=100)),
                ('resolved_predictions_count', models.PositiveIntegerField(default=0)),
                ('accuracy_indicator', models.CharField(default='0%', max_length=16)),
                ('streak', models.PositiveIntegerField(default=0)),
                ('strong_category', models.CharField(blank=True, max_length=80)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_user_reputations',
                'indexes': [models.Index(fields=['-reputation_score', 'last_updated_at'], name='gotrendlabs_reputat_55708c_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('earned', 'Earned'), ('locked', 'Locked')], default='locked', max_length=16)),
                ('earned_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_user_badges',
                'indexes': [models.Index(fields=['user', 'status'], name='gotrendlabs_user_id_2fadaf_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='userbadge',
            constraint=models.UniqueConstraint(fields=('user', 'code'), name='uniq_user_badge_code'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', '-occurred_at'], name='gotrendlabs_user_id_15ff1f_idx'),
        ),
    ]
