# Generated by Django 4.2.30 on 2026-05-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_walletbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('deactivated', 'Deactivated')], default='active', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='authevent',
            name='event_type',
            field=models.CharField(choices=[('register', 'Register'), ('login_success', 'Login success'), ('login_failure', 'Login failure'), ('logout', 'Logout'), ('session_check', 'Session check'), ('account_deletion_requested', 'Account deletion requested')], max_length=40),
        ),
    ]
