# Generated by Django 4.2.30 on 2026-05-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_badgedefinition_userbadgeaward_badgerule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgedefinition',
            name='image_dark_url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
