# Generated by Django 4.2.30 on 2026-05-20 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authevent',
            name='event_type',
            field=models.CharField(choices=[('register', 'Register'), ('login_success', 'Login success'), ('login_failure', 'Login failure'), ('logout', 'Logout'), ('session_check', 'Session check'), ('account_deletion_requested', 'Account deletion requested'), ('password_reset_requested', 'Password reset requested'), ('password_reset_confirmed', 'Password reset confirmed')], max_length=40),
        ),
    ]
