# Generated by Codex on 2026-06-05

from django.db import migrations, models


def confirm_existing_users(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(email_confirmed_at__isnull=True).update(email_confirmed_at=models.F("date_joined"))


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_gotrendlabs_email_domains"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(confirm_existing_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="authevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("register", "Register"),
                    ("login_success", "Login success"),
                    ("login_failure", "Login failure"),
                    ("logout", "Logout"),
                    ("session_check", "Session check"),
                    ("account_deletion_requested", "Account deletion requested"),
                    ("password_reset_requested", "Password reset requested"),
                    ("password_reset_confirmed", "Password reset confirmed"),
                    ("email_confirmation_sent", "Email confirmation sent"),
                    ("email_confirmed", "Email confirmed"),
                ],
                max_length=40,
            ),
        ),
    ]
