# Generated by Django 4.2.30 on 2026-06-06 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_email_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_gtl', models.PositiveIntegerField()),
                ('rewarded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invitee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_reward_received', to=settings.AUTH_USER_MODEL)),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_reward', to='accounts.walletledgerentry')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_rewards_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_referral_rewards',
                'indexes': [models.Index(fields=['referrer', '-created_at'], name='gotrendlabs_referre_414ff0_idx'), models.Index(fields=['invitee'], name='gotrendlabs_invitee_509d76_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referrer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_code', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_referral_codes',
                'indexes': [models.Index(fields=['code'], name='gotrendlabs_code_c61ecd_idx')],
            },
        ),
    ]
