# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0002_market_admin_notes_market_canceled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="market",
            name="auto_close_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="market",
            name="close_timezone",
            field=models.CharField(blank=True, default="America/Sao_Paulo", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="market",
            name="image_url",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
