# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0003_market_auto_close_enabled_market_close_timezone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="marketcategory",
            name="blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketcategory",
            name="blocked_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="marketcategory",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="marketsubcategory",
            name="blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="marketsubcategory",
            name="blocked_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="marketsubcategory",
            name="is_blocked",
            field=models.BooleanField(default=False),
        ),
    ]
