# Generated by Django 4.2.30 on 2026-05-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0008_decimal_probabilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='primary_probability',
        ),
        migrations.RemoveField(
            model_name='market',
            name='secondary_probability',
        ),
        migrations.RemoveField(
            model_name='marketoption',
            name='probability',
        ),
    ]
