# Generated by Django 4.2.30 on 2026-05-18 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0011_market_is_featured'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='market',
            name='uniq_single_featured_market',
        ),
    ]
