# Generated by Codex on 2026-05-18

from django.db import migrations


def clear_canceled_featured(apps, schema_editor):
    Market = apps.get_model("markets", "Market")
    Market.objects.filter(status="canceled", is_featured=True).update(is_featured=False)


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0012_remove_market_uniq_single_featured_market"),
    ]

    operations = [
        migrations.RunPython(clear_canceled_featured, migrations.RunPython.noop),
    ]
