# Generated by Django 4.2.30 on 2026-06-18 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0025_remove_prediction_uniq_prediction_user_market_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='primary_probability_exact',
        ),
        migrations.RemoveField(
            model_name='market',
            name='secondary_probability_exact',
        ),
    ]
