# Generated by Django 4.2.30 on 2026-09-06 15:13

import os

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def grant_runtime_access(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    configured_roles = {
        schema_editor.connection.settings_dict.get("USER"),
        os.environ.get("FASTAPI_POSTGRES_USER"),
        os.environ.get("POSTGRES_USER"),
        os.environ.get("DJANGO_POSTGRES_USER"),
    }
    quote_name = schema_editor.connection.ops.quote_name
    with schema_editor.connection.cursor() as cursor:
        for role in sorted(item for item in configured_roles if item):
            cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = %s", [role])
            if not cursor.fetchone():
                continue
            cursor.execute(
                f"GRANT SELECT, INSERT, UPDATE ON TABLE gotrendlabs_integrity_alerts TO {quote_name(role)}"
            )
            cursor.execute("SELECT pg_get_serial_sequence('gotrendlabs_integrity_alerts', 'id')")
            sequence_row = cursor.fetchone()
            if sequence_row and sequence_row[0]:
                cursor.execute(f"GRANT USAGE, SELECT ON SEQUENCE {sequence_row[0]} TO {quote_name(role)}")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0029_integrity_signing_keys'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('issue_code', models.CharField(db_index=True, max_length=80)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('severity', models.CharField(default='high', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed')], db_index=True, default='pending', max_length=20)),
                ('occurrences', models.PositiveIntegerField(default=1)),
                ('first_detected_at', models.DateTimeField()),
                ('last_detected_at', models.DateTimeField()),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='integrity_alerts', to='markets.market')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_integrity_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_integrity_alerts',
                'indexes': [models.Index(fields=['status', '-last_detected_at'], name='gtl_ialert_status_seen_idx'), models.Index(fields=['market', 'status'], name='gtl_ialert_market_status_idx')],
            },
        ),
        migrations.RunPython(grant_runtime_access, migrations.RunPython.noop),
    ]
