# Generated by Django 4.2.30 on 2026-10-07 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('editorial_integrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('markets', '0031_integrity_ledger_checkpoints'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminevent',
            name='execution_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='adminevent',
            name='integration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='editorial_integrations.integration'),
        ),
        migrations.AddField(
            model_name='adminevent',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='adminevent',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_admin_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
