# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_ops", "0004_siteconfig_ai_agent_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="ai_comment_candidate_limit",
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="ai_max_comment_attempts_per_cycle",
            field=models.PositiveIntegerField(default=3),
        ),
    ]
