# Generated by Codex on 2026-05-24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_ops", "0005_siteconfig_ai_comment_attempt_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="ai_audit_retention_days",
            field=models.PositiveIntegerField(default=90),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="system_log_retention_days",
            field=models.PositiveIntegerField(default=90),
        ),
    ]
