# Generated by Django 4.2.30 on 2026-06-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0007_gotrendlabs_rebrand'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='referral_bonus_gtl',
            field=models.PositiveIntegerField(default=200),
        ),
    ]
