# Generated by Codex on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_ops", "0008_siteconfig_referral_bonus_gtl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="daemon_missing_after_minutes",
            field=models.PositiveIntegerField(default=21),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="daemon_stale_after_minutes",
            field=models.PositiveIntegerField(default=7),
        ),
    ]
