# Generated by Django 4.2.30 on 2026-06-08 21:10

import apps.web.django.admin_ops.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_ops', '0009_siteconfig_daemon_threshold_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAppRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android')], default='android', max_length=20)),
                ('version_name', models.CharField(max_length=40)),
                ('version_code', models.PositiveIntegerField()),
                ('apk', models.FileField(upload_to=apps.web.django.admin_ops.models.mobile_app_release_upload_to)),
                ('sha256', models.CharField(blank=True, editable=False, max_length=64)),
                ('file_size', models.PositiveBigIntegerField(default=0, editable=False)),
                ('release_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_mobile_app_releases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_mobile_app_releases',
                'ordering': ['-published_at', '-created_at', '-id'],
                'indexes': [models.Index(fields=['platform', 'is_active'], name='gtl_mobrel_platform_active_idx'), models.Index(fields=['platform', 'version_code'], name='gtl_mobrel_plat_ver_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='mobileapprelease',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('platform',), name='uniq_active_mobile_release_per_platform'),
        ),
    ]
