# Generated by Django 4.2.30 on 2026-06-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_ops', '0012_remove_legacy_email_residue'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='position_reinforcement_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='position_reinforcement_min_gtl',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='position_revision_cutoff_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='position_revision_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='position_revision_max_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='position_revision_min_remaining_gtl',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='position_revision_penalty_percent',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
