# Generated by Django 4.2.30 on 2026-06-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_ops", "0014_siteconfig_position_db_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="position_reinforcement_max_count",
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE gotrendlabs_site_config
              ALTER COLUMN position_reinforcement_max_count SET DEFAULT 3
            """,
            """
            ALTER TABLE gotrendlabs_site_config
              ALTER COLUMN position_reinforcement_max_count DROP DEFAULT
            """,
        ),
    ]
