# Generated by Django 4.2.30 on 2026-06-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_ops", "0015_siteconfig_position_reinforcement_max_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="ai_max_comments_per_market",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
