from django.db import migrations


def create_status_tables(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            CREATE TABLE gotrendlabs_analytics_ingestion_status (
                id smallint PRIMARY KEY CHECK (id = 1),
                completed_at timestamptz NOT NULL,
                platform varchar(16) NOT NULL,
                received integer NOT NULL CHECK (received >= 0),
                accepted integer NOT NULL CHECK (accepted >= 0),
                new_session boolean NOT NULL
            )
        """)
        cursor.execute("""
            CREATE TABLE gotrendlabs_geolite_load_runs (
                id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                started_at timestamptz NOT NULL,
                completed_at timestamptz NOT NULL,
                status varchar(16) NOT NULL CHECK (status IN ('success', 'failed')),
                database_build_at timestamptz,
                database_type varchar(80),
                file_size_bytes bigint,
                node_count bigint,
                error_code varchar(80)
            )
        """)
        cursor.execute("CREATE INDEX gtl_geolite_load_runs_latest ON gotrendlabs_geolite_load_runs (completed_at DESC, id DESC)")
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname = 'gotrendlabs_fastapi'")
        if cursor.fetchone():
            cursor.execute("GRANT SELECT, INSERT, UPDATE ON gotrendlabs_analytics_ingestion_status TO gotrendlabs_fastapi")
            cursor.execute("GRANT SELECT, INSERT ON gotrendlabs_geolite_load_runs TO gotrendlabs_fastapi")
            cursor.execute("GRANT USAGE, SELECT ON SEQUENCE gotrendlabs_geolite_load_runs_id_seq TO gotrendlabs_fastapi")


def drop_status_tables(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE gotrendlabs_geolite_load_runs")
        cursor.execute("DROP TABLE gotrendlabs_analytics_ingestion_status")


class Migration(migrations.Migration):
    dependencies = [("admin_ops", "0020_first_party_analytics")]
    operations = [migrations.RunPython(create_status_tables, drop_status_tables)]
