# Generated by Django 4.2.30 on 2026-10-09 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def defaults_and_grants(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE gotrendlabs_thumbnail_jobs ALTER COLUMN created_at SET DEFAULT now()"
        )
        cursor.execute(
            "ALTER TABLE gotrendlabs_thumbnail_jobs ALTER COLUMN error_code SET DEFAULT ''"
        )
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname='gotrendlabs_django'")
        if cursor.fetchone():
            cursor.execute(
                "REVOKE ALL ON gotrendlabs_thumbnail_jobs FROM gotrendlabs_django"
            )
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname='gotrendlabs_fastapi'")
        if cursor.fetchone():
            cursor.execute(
                "GRANT SELECT, INSERT, UPDATE, DELETE ON gotrendlabs_thumbnail_jobs TO gotrendlabs_fastapi"
            )


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0032_adminevent_execution_id_adminevent_integration_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("admin_ops", "0021_analytics_load_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThumbnailJob",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("session_id", models.BigIntegerField()),
                ("snapshot", models.JSONField()),
                ("snapshot_hash", models.CharField(max_length=64)),
                ("instructions_version", models.CharField(max_length=40)),
                ("orchestrator", models.CharField(max_length=100)),
                ("image_model", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField()),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                ("claim_token", models.UUIDField(null=True)),
                ("expires_at", models.DateTimeField()),
                ("provider_id", models.CharField(max_length=160, null=True)),
                ("usage", models.JSONField(null=True)),
                ("error_code", models.CharField(default="", max_length=60)),
                ("applied_at", models.DateTimeField(null=True)),
                ("public_name", models.CharField(max_length=100, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "market",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="markets.market"
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gotrendlabs_thumbnail_jobs",
                "indexes": [
                    models.Index(
                        fields=["created_at", "operator", "market"],
                        name="gtl_thumb_quota",
                    ),
                    models.Index(
                        condition=models.Q(("state", "queued")),
                        fields=["created_at"],
                        name="gtl_thumb_queue",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="thumbnailjob",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "state__in",
                        [
                            "queued",
                            "running",
                            "succeeded",
                            "failed",
                            "uncertain",
                            "expired",
                        ],
                    )
                ),
                name="gtl_thumb_state",
            ),
        ),
        migrations.AddConstraint(
            model_name="thumbnailjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state__in", ["queued", "running"])),
                fields=("market",),
                name="gtl_thumb_one_active",
            ),
        ),
        migrations.RunPython(defaults_and_grants, migrations.RunPython.noop),
    ]
