# Generated by Django 4.2.30 on 2026-10-09 12:50

from django.db import migrations, models


def grants(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname='gotrendlabs_fastapi'")
        if cursor.fetchone():
            cursor.execute(
                "GRANT SELECT ON gotrendlabs_site_config TO gotrendlabs_fastapi"
            )
            cursor.execute(
                "GRANT UPDATE (thumbnail_enabled, thumbnail_model, thumbnail_region, thumbnail_aspect_ratio, thumbnail_timeout_seconds, thumbnail_operator_limit, thumbnail_market_limit, thumbnail_global_limit, thumbnail_period_hours, thumbnail_retention_hours, updated_by_id, updated_at) ON gotrendlabs_site_config TO gotrendlabs_fastapi"
            )


class Migration(migrations.Migration):
    dependencies = [
        ("admin_ops", "0022_thumbnail_jobs"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="thumbnail_aspect_ratio",
            field=models.CharField(default="3:2", max_length=10),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="thumbnail_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="thumbnail_global_limit",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="thumbnail_market_limit",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="thumbnail_model",
            field=models.CharField(
                default="stability.stable-image-core-v1:1", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="thumbnail_operator_limit",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="thumbnail_period_hours",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="thumbnail_region",
            field=models.CharField(default="us-west-2", max_length=40),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="thumbnail_retention_hours",
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="thumbnail_timeout_seconds",
            field=models.PositiveIntegerField(default=180),
        ),
        migrations.AddField(
            model_name="thumbnailjob",
            name="provider",
            field=models.CharField(default="openai", max_length=40),
        ),
        migrations.AlterField(
            model_name="thumbnailjob",
            name="provider",
            field=models.CharField(default="bedrock", max_length=40),
        ),
        migrations.AddField(
            model_name="thumbnailjob",
            name="provider_config",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(grants, migrations.RunPython.noop),
    ]
