# Generated by Django 4.2.30 on 2026-10-09 16:57

from django.db import migrations, models
import django.db.models.deletion


def runtime_defaults_and_grants(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            "ALTER TABLE gotrendlabs_site_config ALTER COLUMN badge_image_enabled SET DEFAULT false"
        )
        cursor.execute(
            "ALTER TABLE gotrendlabs_thumbnail_jobs ALTER COLUMN kind SET DEFAULT 'market'"
        )
        cursor.execute("SELECT 1 FROM pg_roles WHERE rolname='gotrendlabs_fastapi'")
        if cursor.fetchone():
            cursor.execute(
                "GRANT UPDATE (badge_image_enabled) ON gotrendlabs_site_config TO gotrendlabs_fastapi"
            )


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0024_grant_mfa_runtime_permissions"),
        ("markets", "0032_adminevent_execution_id_adminevent_integration_and_more"),
        ("admin_ops", "0024_thumbnail_runtime_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="badge_image_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="thumbnailjob",
            name="badge",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.badgedefinition",
            ),
        ),
        migrations.AddField(
            model_name="thumbnailjob",
            name="editor_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name="thumbnailjob",
            name="kind",
            field=models.CharField(default="market", max_length=16),
        ),
        migrations.AlterField(
            model_name="thumbnailjob",
            name="market",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="markets.market",
            ),
        ),
        migrations.AddConstraint(
            model_name="thumbnailjob",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("badge__isnull", True),
                        ("editor_id__isnull", True),
                        ("kind", "market"),
                        ("market__isnull", False),
                    ),
                    models.Q(
                        ("editor_id__isnull", False),
                        ("kind", "badge"),
                        ("market__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="gtl_image_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="thumbnailjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("badge__isnull", False),
                    ("kind", "badge"),
                    ("state__in", ["queued", "running"]),
                ),
                fields=("badge",),
                name="gtl_badge_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="thumbnailjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("badge__isnull", True),
                    ("kind", "badge"),
                    ("state__in", ["queued", "running"]),
                ),
                fields=("operator", "editor_id"),
                name="gtl_badge_editor_active",
            ),
        ),
        migrations.RunPython(runtime_defaults_and_grants, migrations.RunPython.noop),
    ]
