# Generated by Django 4.2.30 on 2026-05-17 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils import timezone


def backfill_wallet_balances(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    WalletBalance = apps.get_model("accounts", "WalletBalance")
    WalletLedgerEntry = apps.get_model("accounts", "WalletLedgerEntry")

    for user in User.objects.all().iterator():
        entries = WalletLedgerEntry.objects.filter(user_id=user.id)
        available_oc = 0
        locked_oc = 0
        total_earned_oc = 0
        for entry in entries:
            if entry.direction == "credit":
                available_oc += entry.amount
                if entry.entry_type in ("prediction_payout", "reward_feedback", "reward_suggestion"):
                    total_earned_oc += entry.amount
            elif entry.direction == "debit":
                available_oc -= entry.amount
            elif entry.direction == "lock":
                locked_oc += entry.amount
            elif entry.direction == "release":
                locked_oc -= entry.amount

        WalletBalance.objects.update_or_create(
            user_id=user.id,
            defaults={
                "available_oc": available_oc,
                "locked_oc": locked_oc,
                "total_earned_oc": total_earned_oc,
                "updated_at": timezone.now(),
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_useractivity_walletledgerentry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_oc', models.IntegerField(default=0)),
                ('locked_oc', models.IntegerField(default=0)),
                ('total_earned_oc', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orynth_wallet_balances',
            },
        ),
        migrations.RunPython(backfill_wallet_balances, migrations.RunPython.noop),
    ]
