# Generated by Codex on 2026-05-18

from django.db import migrations


def prefix_user_handles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.exclude(username__startswith="@").iterator():
        base = f"@{user.username.lstrip('@')}"[:150] or "@user"
        candidate = base
        suffix = 2
        while User.objects.filter(username__iexact=candidate).exclude(id=user.id).exists():
            suffix_text = str(suffix)
            candidate = f"{base[:150 - len(suffix_text)]}{suffix_text}"
            suffix += 1
        user.username = candidate
        user.save(update_fields=["username"])


def unprefix_user_handles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.filter(username__startswith="@").iterator():
        user.username = user.username[1:] or "user"
        user.save(update_fields=["username"])


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_user_account_status_user_deactivated_at_and_more"),
    ]

    operations = [
        migrations.RunPython(prefix_user_handles, unprefix_user_handles),
    ]
