# Generated by Codex on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_prefix_user_handles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="walletledgerentry",
            name="direction",
            field=models.CharField(
                choices=[
                    ("credit", "Credit"),
                    ("debit", "Debit"),
                    ("lock", "Lock"),
                    ("release", "Release"),
                    ("settle", "Settle"),
                ],
                max_length=16,
            ),
        ),
    ]
