# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_wallet_ledger_settle_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[
                    ("male", "Masculino"),
                    ("female", "Feminino"),
                    ("other", "Outro"),
                    ("prefer_not_to_say", "Prefiro não informar"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
