# Generated by Django 4.2.30 on 2026-05-19 14:17

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
import django.db.models.deletion


DEFAULT_BADGES = [
    {
        "code": "founding_member",
        "name": "Membro fundador",
        "description": "Entrou no Orynth durante a fase inicial.",
        "rule_description": "Concedida ao criar conta na fase inicial.",
        "badge_type": "global",
        "rule_type": "founding_member",
        "threshold_value": 1,
    },
    {
        "code": "first_resolution",
        "name": "Primeira resolução",
        "description": "Participou de uma previsão que já foi resolvida.",
        "rule_description": "Tenha pelo menos 1 previsão resolvida.",
        "badge_type": "global",
        "rule_type": "resolved_predictions_count",
        "threshold_value": 1,
    },
    {
        "code": "ten_resolutions",
        "name": "10 resoluções",
        "description": "Acumulou dez previsões resolvidas.",
        "rule_description": "Tenha pelo menos 10 previsões resolvidas.",
        "badge_type": "global",
        "rule_type": "resolved_predictions_count",
        "threshold_value": 10,
    },
    {
        "code": "five_hits",
        "name": "5 acertos",
        "description": "Acertou cinco previsões resolvidas.",
        "rule_description": "Tenha pelo menos 5 previsões vencedoras.",
        "badge_type": "performance",
        "rule_type": "correct_predictions_count",
        "threshold_value": 5,
    },
    {
        "code": "streak_five",
        "name": "Sequência de 5",
        "description": "Construiu uma sequência de cinco acertos.",
        "rule_description": "Alcance streak de 5 acertos.",
        "badge_type": "performance",
        "rule_type": "streak_count",
        "threshold_value": 5,
    },
    {
        "code": "top_ten",
        "name": "Top 10",
        "description": "Entrou no top 10 do ranking global.",
        "rule_description": "Alcance posição 10 ou melhor no ranking global.",
        "badge_type": "performance",
        "rule_type": "ranking_position",
        "threshold_value": 10,
    },
    {
        "code": "voice_builder",
        "name": "Voz ativa",
        "description": "Contribuiu com comentários em mercados.",
        "rule_description": "Publique pelo menos 5 comentários visíveis.",
        "badge_type": "engagement",
        "rule_type": "comments_count",
        "threshold_value": 5,
    },
    {
        "code": "market_scout",
        "name": "Radar de mercados",
        "description": "Teve sugestão reconhecida pela curadoria.",
        "rule_description": "Tenha pelo menos 1 sugestão aprovada ou recompensada.",
        "badge_type": "engagement",
        "rule_type": "approved_suggestions_count",
        "threshold_value": 1,
    },
    {
        "code": "feedback_ally",
        "name": "Aliado do feedback",
        "description": "Enviou feedback recompensado pela operação.",
        "rule_description": "Tenha pelo menos 1 feedback recompensado.",
        "badge_type": "engagement",
        "rule_type": "rewarded_feedback_count",
        "threshold_value": 1,
    },
]


def seed_badges(apps, schema_editor):
    BadgeDefinition = apps.get_model("accounts", "BadgeDefinition")
    BadgeRule = apps.get_model("accounts", "BadgeRule")
    UserBadge = apps.get_model("accounts", "UserBadge")
    UserBadgeAward = apps.get_model("accounts", "UserBadgeAward")
    now = timezone.now()
    badge_by_code = {}
    for item in DEFAULT_BADGES:
        badge, _ = BadgeDefinition.objects.update_or_create(
            code=item["code"],
            defaults={
                "name": item["name"],
                "description": item["description"],
                "rule_description": item["rule_description"],
                "badge_type": item["badge_type"],
                "is_active": True,
            },
        )
        BadgeRule.objects.update_or_create(
            badge=badge,
            defaults={
                "rule_type": item["rule_type"],
                "threshold_value": item["threshold_value"],
                "category": "",
                "subcategory": "",
                "is_active": True,
            },
        )
        badge_by_code[item["code"]] = badge

    for legacy_badge in UserBadge.objects.filter(status="earned"):
        badge = badge_by_code.get(legacy_badge.code)
        if not badge:
            badge, _ = BadgeDefinition.objects.update_or_create(
                code=legacy_badge.code,
                defaults={
                    "name": legacy_badge.name,
                    "description": legacy_badge.description,
                    "rule_description": legacy_badge.description,
                    "badge_type": "global",
                    "is_active": True,
                },
            )
            BadgeRule.objects.get_or_create(
                badge=badge,
                defaults={
                    "rule_type": "founding_member",
                    "threshold_value": 1,
                    "category": "",
                    "subcategory": "",
                    "is_active": False,
                },
            )
            badge_by_code[legacy_badge.code] = badge
        UserBadgeAward.objects.get_or_create(
            user_id=legacy_badge.user_id,
            badge=badge,
            defaults={
                "awarded_at": legacy_badge.earned_at or now,
                "reason_snapshot": legacy_badge.description,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_birth_date_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=255)),
                ('rule_description', models.CharField(blank=True, max_length=255)),
                ('badge_type', models.CharField(choices=[('global', 'Global'), ('category', 'Category'), ('performance', 'Performance'), ('engagement', 'Engagement')], default='global', max_length=32)),
                ('image_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'orynth_badge_definitions',
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserBadgeAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_at', models.DateTimeField()),
                ('reason_snapshot', models.CharField(blank=True, max_length=255)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='accounts.badgedefinition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badge_awards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orynth_user_badge_awards',
            },
        ),
        migrations.CreateModel(
            name='BadgeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('founding_member', 'Founding member'), ('resolved_predictions_count', 'Resolved predictions count'), ('correct_predictions_count', 'Correct predictions count'), ('streak_count', 'Streak count'), ('ranking_position', 'Ranking position'), ('comments_count', 'Comments count'), ('approved_suggestions_count', 'Approved suggestions count'), ('rewarded_feedback_count', 'Rewarded feedback count')], max_length=64)),
                ('threshold_value', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('subcategory', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('badge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rule', to='accounts.badgedefinition')),
            ],
            options={
                'db_table': 'orynth_badge_rules',
            },
        ),
        migrations.AddIndex(
            model_name='badgedefinition',
            index=models.Index(fields=['is_active', 'badge_type'], name='orynth_badg_is_acti_b37fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadgeaward',
            index=models.Index(fields=['user', '-awarded_at'], name='orynth_user_user_id_59b1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='userbadgeaward',
            index=models.Index(fields=['badge', '-awarded_at'], name='orynth_user_badge_i_eb1e38_idx'),
        ),
        migrations.AddConstraint(
            model_name='userbadgeaward',
            constraint=models.UniqueConstraint(fields=('user', 'badge'), name='uniq_user_badge_award'),
        ),
        migrations.AddIndex(
            model_name='badgerule',
            index=models.Index(fields=['rule_type', 'is_active'], name='orynth_badg_rule_ty_6ca51a_idx'),
        ),
        migrations.RunPython(seed_badges, migrations.RunPython.noop),
    ]
