# Generated by Codex on 2026-05-20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_alter_authevent_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletRechargeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("pending", "Pending"), ("approved", "Approved"), ("rejected", "Rejected")], db_index=True, default="pending", max_length=20)),
                ("amount_oc", models.PositiveIntegerField(blank=True, null=True)),
                ("admin_note", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_wallet_recharge_requests", to=settings.AUTH_USER_MODEL)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="wallet_recharge_requests", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "orynth_wallet_recharge_requests",
            },
        ),
        migrations.AddIndex(
            model_name="walletrechargerequest",
            index=models.Index(fields=["status", "-created_at"], name="orynth_wall_status_07af12_idx"),
        ),
        migrations.AddIndex(
            model_name="walletrechargerequest",
            index=models.Index(fields=["user", "-created_at"], name="orynth_wall_user_id_173962_idx"),
        ),
        migrations.AddConstraint(
            model_name="walletrechargerequest",
            constraint=models.UniqueConstraint(condition=models.Q(("status", "pending")), fields=("user",), name="uniq_pending_wallet_recharge_user"),
        ),
    ]
