# Generated by Django 4.2.30 on 2026-06-08 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


DEFAULT_PUSH_EVENTS = {
    "market_resolved": {
        "mode": "immediate",
        "priority": 10,
        "title": "Resultado publicado",
        "body": "{{ market_title|default:\"Um mercado\" }} foi resolvido. Abra o app para ver o resultado.",
        "allowed_variables": ["market_title", "market_slug", "notification_id"],
    },
    "market_locked": {
        "mode": "immediate",
        "priority": 20,
        "title": "Mercado em apuração",
        "body": "{{ market_title|default:\"Um mercado\" }} fechou para novas previsões",
        "allowed_variables": ["market_title", "market_slug", "notification_id"],
    },
    "wallet_credit": {
        "mode": "immediate",
        "priority": 30,
        "title": "Carteira atualizada",
        "body": "Sua carteira educativa foi atualizada. Confira no app.",
        "allowed_variables": ["notification_id"],
    },
    "badge_awarded": {
        "mode": "immediate",
        "priority": 40,
        "title": "Nova badge",
        "body": "Você desbloqueou {{ badge_name|default:\"uma nova badge\" }}.",
        "allowed_variables": ["badge_code", "badge_name", "notification_id"],
    },
    "market_comment": {
        "mode": "immediate",
        "priority": 50,
        "title": "Novo comentário",
        "body": "{{ actor_handle|default:\"Alguém\" }} comentou em {{ market_title|default:\"um mercado\" }}",
        "allowed_variables": ["actor_handle", "market_title", "market_slug", "comment_id", "notification_id"],
    },
    "comment_like": {
        "mode": "immediate",
        "priority": 60,
        "title": "Curtida no comentário",
        "body": "{{ actor_handle|default:\"Alguém\" }} curtiu seu comentário.",
        "allowed_variables": ["actor_handle", "market_slug", "comment_id", "notification_id"],
    },
    "market_prediction": {
        "mode": "off",
        "priority": 70,
        "title": "Nova previsão no mercado",
        "body": "{{ actor_handle|default:\"Alguém\" }} fez uma previsão em {{ market_title|default:\"um mercado\" }}",
        "allowed_variables": ["actor_handle", "market_title", "market_slug", "notification_id"],
    },
    "market_like": {
        "mode": "off",
        "priority": 80,
        "title": "Mercado curtido",
        "body": "{{ actor_handle|default:\"Alguém\" }} curtiu {{ market_title|default:\"um mercado\" }}",
        "allowed_variables": ["actor_handle", "market_title", "market_slug", "notification_id"],
    },
}


def seed_push_defaults(apps, schema_editor):
    PushEventPolicy = apps.get_model("communications", "PushEventPolicy")
    PushTemplate = apps.get_model("communications", "PushTemplate")
    for event_type, payload in DEFAULT_PUSH_EVENTS.items():
        allowed_variables = payload["allowed_variables"]
        PushEventPolicy.objects.update_or_create(
            event_type=event_type,
            defaults={
                "mode": payload["mode"],
                "is_active": True,
                "default_user_enabled": True,
                "priority": payload["priority"],
                "template_key": event_type,
                "allowed_variables": allowed_variables,
            },
        )
        PushTemplate.objects.update_or_create(
            event_type=event_type,
            locale="pt-br",
            defaults={
                "title": payload["title"],
                "body": payload["body"],
                "is_active": True,
                "allowed_variables": allowed_variables,
            },
        )


def remove_push_defaults(apps, schema_editor):
    PushEventPolicy = apps.get_model("communications", "PushEventPolicy")
    PushTemplate = apps.get_model("communications", "PushTemplate")
    event_types = list(DEFAULT_PUSH_EVENTS)
    PushEventPolicy.objects.filter(event_type__in=event_types).delete()
    PushTemplate.objects.filter(event_type__in=event_types).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('markets', '0024_gotrendlabs_legacy_market_funnel_tables'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communications', '0002_polish_ptbr_email_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, default='', max_length=80)),
                ('push_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_push_preferences',
                'ordering': ['event_type', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PushEventPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80, unique=True)),
                ('mode', models.CharField(choices=[('off', 'Off'), ('immediate', 'Immediate'), ('digest', 'Digest')], default='off', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('default_user_enabled', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('template_key', models.CharField(blank=True, max_length=80)),
                ('allowed_variables', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gotrendlabs_push_event_policies',
                'ordering': ['priority', 'event_type'],
                'indexes': [models.Index(fields=['event_type', 'is_active'], name='gotrendlabs_event_t_38f23b_idx'), models.Index(fields=['mode', 'is_active'], name='gotrendlabs_mode_88b783_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('fcm', 'FCM')], default='fcm', max_length=20)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('token', models.TextField()),
                ('token_hash', models.CharField(db_index=True, max_length=64)),
                ('app_version', models.CharField(blank=True, max_length=40)),
                ('build_number', models.CharField(blank=True, max_length=40)),
                ('device_label', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('provider_invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_reason', models.CharField(blank=True, max_length=120)),
                ('last_registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_push_devices',
                'ordering': ['-last_registered_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('provider', models.CharField(default='fcm', max_length=20)),
                ('template_key', models.CharField(blank=True, max_length=80)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('policy_snapshot', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=191, unique=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('suppressed', 'Suppressed'), ('dry_run', 'Dry run'), ('invalid_token', 'Invalid token')], default='queued', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='communications.pushdevice')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_deliveries', to='markets.usernotification')),
            ],
            options={
                'db_table': 'gotrendlabs_push_deliveries',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PushTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=80)),
                ('locale', models.CharField(choices=[('pt-br', 'PT-BR'), ('en', 'EN')], default='pt-br', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('allowed_variables', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_push_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gotrendlabs_push_templates',
                'ordering': ['event_type', 'locale'],
                'indexes': [models.Index(fields=['event_type', 'locale', 'is_active'], name='gotrendlabs_event_t_6d5879_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='pushtemplate',
            constraint=models.UniqueConstraint(fields=('event_type', 'locale'), name='uniq_push_template_event_locale'),
        ),
        migrations.AddIndex(
            model_name='pushpreference',
            index=models.Index(fields=['user', 'event_type'], name='gotrendlabs_user_id_9468d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushpreference',
            constraint=models.UniqueConstraint(fields=('user', 'event_type'), name='uniq_push_preference_user_event'),
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['user', 'is_active', '-last_registered_at'], name='gtl_pushdev_user_active_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdevice',
            index=models.Index(fields=['provider', 'token_hash'], name='gtl_pushdev_provider_token_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushdevice',
            constraint=models.UniqueConstraint(fields=('user', 'provider', 'token_hash'), name='uniq_push_device_user_provider_token'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='gotrendlabs_status_a9202c_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['event_type', '-created_at'], name='gotrendlabs_event_t_3ee5af_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['device', '-created_at'], name='gotrendlabs_device__cdb593_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['notification', 'device'], name='gotrendlabs_notific_36f803_idx'),
        ),
        migrations.RunPython(seed_push_defaults, remove_push_defaults),
    ]
